spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/cartaesercito
    password: Entando2022
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
app:
  csv:
    folder: /Users/germano/projects/SME/sme-ce-integration-layers/files/
  query:
    nucleoFamiliarePrincipaleSponsor: |
      select * from tabnucleifull
      join tabsoggetto on tabnucleifull.rif_soggetto=tabsoggetto.idSoggetto
      where rif_istanza = 
      (select idIstanza from tabistanza 
      where id_sponsor=(select idSoggetto from tabsoggetto where codiceFiscale=:codiceFiscale)
      and rif_tipoIstanza in (1, 3) ORDER BY idIstanza DESC LIMIT 1);
    nucleoFamiliareEsternoSponsor: |
      select * from tabnucleifull
      join tabsoggetto on tabnucleifull.rif_soggetto=tabsoggetto.idSoggetto
      where rif_istanza = 
      (select idIstanza from tabistanza 
      where id_sponsor=(select idSoggetto from tabsoggetto where codiceFiscale=:codiceFiscale)
      and rif_tipoIstanza in (4, 5) ORDER BY idIstanza DESC LIMIT 1);
