spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/cartaesercito
    password: Entando2022
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
app:
  config:
      soggetto:
        rifStato: 1
      istanza:
        rifCanale: 1
        rifOperatore: 1
        rifStatoIstanza: 1
        nucleoPrincipale: 1
        itegrNucleoPrincipale: 3
        nucleoEsterno: 4
        integrNucleoEsterno: 5
      mandato:
        rifOperatore: 1
        rifOperatorePagamento: 1
        rifStatoMandato: 1
        rifTipoPagamento: 1
      costi:
        perSponsor: 800
        perFamigliare: 400
        perOspite: 1000
        spedizione: 450
        limiteNucleoFamigliarePrincipaleNoSponsor: 2000
      query:
        carteEsercitoPerSponsor: |
          select tabnucleifull.rif_nucleo as rifNucleo,
          tabistanza.rif_tipoIstanza as rifTipoIstanza,
          tabsoggetto.nome,
          tabsoggetto.cognome,
          tabsoggetto.email,
          tabsoggetto.enteAppartenenza,
          tabsoggetto.fototessera,
          tabsoggetto.nascitaData,
          tabsoggetto.nascitaLuogo,
          tabsoggetto.nazionalita,
          tabsoggetto.rif_gradoQualifica as rifGradoQualifica,
          tabsoggetto.rif_posizione as rifPosizione,
          tabsoggetto.rif_rapporto as rifRapporto,
          tabsoggetto.sesso,
          tabsoggetto.telCellulare,
          tabsoggetto.telUfficio,
          tabsoggetto.codiceFiscale,
          tabnucleifull.is_sponsor as isSponsor,
          tabistanza.rif_statoIstanza as rifStatoIstanza,
          tabcartaesercito.numeroCarta,
          tabcartaesercito.rif_statoCarta as rifStatoCarta,
          tabcartaesercito.dataScadenzaCarta,
          tabcartaesercito.dataRilascioCarta,
          tabsoggetto.rif_stato as rifStato
          from tabnucleifull
             join tabistanza on tabistanza.idIstanza = tabnucleifull.rif_istanza
             join tabsoggetto on tabsoggetto.idSoggetto = tabnucleifull.rif_soggetto
             left join tabcartaesercito on tabnucleifull.rif_soggetto = tabcartaesercito.rif_soggetto
          where tabistanza.id_sponsor = (select tabsoggetto.idSoggetto from tabsoggetto where tabsoggetto.codiceFiscale=:codiceFiscale)
  

